### ISSUE TITLE
Inheritance of custom attributes could get missing after rename

### ISSUE THREAD

**Issue by wmjordan** [mkaring/ConfuserEx#123]
Reproduction code and project below:
[ConsoleApp1.zip](https://github.com/mkaring/ConfuserEx/files/4190410/ConsoleApp1.zip)

````CSharp
	interface I<TM>
	{
		TM T { get; }
	}
	abstract class C : I<DayOfWeek>
	{
		public abstract DayOfWeek T { get; }
	}
	sealed class D : C
	{
		public override DayOfWeek T { get => DayOfWeek.Monday; }
	}
````
When the above code is obfuscated, the `D.T` no longer overrides `C.T`.

Maybe there is something to do with the `sealed` keyword.

PS: I am using the latest released version 1.3.1.

**Comment by wmjordan** [comment]
We can read the following IL for the class `D` if we ildasm the protected assembly.
We can see that the overrided member is `get_T`, however it has already been renamed.

````
.class private auto ansi sealed beforefieldinit '​⁬⁪‍⁮⁪‫‫‫​‮⁪‍​‍⁯⁪‏‌‪⁪‫‫‏‮⁯⁬⁬‍⁪⁯‫‍‭‌‮‌⁮‫‮'
	extends '⁪‏⁮⁬⁯‏‫‌​‏‮‪⁯‪‏‎‍⁪‍‭‎⁪‮‎⁬‎‫‮‍⁭‫⁮‭‬‏‍‮⁪⁭⁭‮'
{
	// Methods
	.method public hidebysig specialname rtspecialname 
		instance void .ctor () cil managed 
	{
		.maxstack 3
		.locals init (
			[0] uint32
		)

		/* 02           */ IL_0000: ldarg.0
		/* 2841000006   */ IL_0001: call      instance void '⁪‏⁮⁬⁯‏‫‌​‏‮‪⁯‪‏‎‍⁪‍‭‎⁪‮‎⁬‎‫‮‍⁭‫⁮‭‬‏‍‮⁪⁭⁭‮'::.ctor()
		/* 2A           */ IL_0006: ret
	} // end of method '​⁬⁪‍⁮⁪‫‫‫​‮⁪‍​‍⁯⁪‏‌‪⁪‫‫‏‮⁯⁬⁬‍⁪⁯‫‍‭‌‮‌⁮‫‮'::.ctor

	.method public hidebysig specialname virtual 
		instance valuetype [mscorlib]System.DayOfWeek '⁯‏‎‫‫‭‌‎‌⁫‬‬⁭​⁮⁯‎‫⁯​⁯‌‫‫⁯‫‬⁬‫‭‪⁪⁪‭‌‪‌‮⁫⁭‮' () cil managed 
	{
		.override method instance valuetype [mscorlib]System.DayOfWeek '⁪‏⁮⁬⁯‏‫‌​‏‮‪⁯‪‏‎‍⁪‍‭‎⁪‮‎⁬‎‫‮‍⁭‫⁮‭‬‏‍‮⁪⁭⁭‮'::get_T()
		.maxstack 3
		.locals init (
			[0] uint32
		)
		/* 17           */ IL_0000: ldc.i4.1
		/* 2A           */ IL_0001: ret
	} // end of method '​⁬⁪‍⁮⁪‫‫‫​‮⁪‍​‍⁯⁪‏‌‪⁪‫‫‏‮⁯⁬⁬‍⁪⁯‫‍‭‌‮‌⁮‫‮'::'⁯‏‎‫‫‭‌‎‌⁫‬‬⁭​⁮⁯‎‫⁯​⁯‌‫‫⁯‫‬⁬‫‭‪⁪⁪‭‌‪‌‮⁫⁭‮'

	// Properties
	.property instance valuetype [mscorlib]System.DayOfWeek '‬‍‌‮⁪⁪‏‍‌‌‮‪⁯‪⁯‍​​⁯⁯‬‫‮‮‪⁭​‍‌‮⁬⁫⁫‏⁫‭‍‍‭‭‮'()
	{
		.get instance valuetype [mscorlib]System.DayOfWeek '​⁬⁪‍⁮⁪‫‫‫​‮⁪‍​‍⁯⁪‏‌‪⁪‫‫‏‮⁯⁬⁬‍⁪⁯‫‍‭‌‮‌⁮‫‮'::'⁯‏‎‫‫‭‌‎‌⁫‬‬⁭​⁮⁯‎‫⁯​⁯‌‫‫⁯‫‬⁬‫‭‪⁪⁪‭‌‪‌‮⁫⁭‮'()
	}

} // end of class ​⁬⁪‍⁮⁪‫‫‫​‮⁪‍​‍⁯⁪‏‌‪⁪‫‫‏‮⁯⁬⁬‍⁪⁯‫‍‭‌‮‌⁮‫‮
````

**Comment by mkaring** [comment]
@wmjordan I looked into this and it seems I can't reproduce the error. The `get_T` method in the class `C` is not getting renamed. So the override signature is fine.

I tried to create a minimal example producing the issue, but failed to do so as well. I'm not able to create any issues at runtime.

I attached the minimal example I tried to create: [ConfuserIssue123.zip](https://github.com/mkaring/ConfuserEx/files/4239268/ConfuserIssue123.zip)

Would be great if you could take a look and see what needs to be changed in order to produce the issue you found.

**Comment by wmjordan** [comment]
Thank you for taking a look in the this problem. The problem was really very obscure. I am sorry that I have wasted your time for not having clearly described it.

If you observe the property name `T` in the class and the interface, you will find that they are **not the same** after the obfuscation. The above IL code did not show that.

I hereby made another one which can better demonstrate the issue. The missing inheritance can be verified with the `Attribute.GetCustomAttributes` method in the Basic Class Library. The program outputs `1`, if it is unprotected, but it crashed with a `System.IndexOutOfRangeException` after the obfuscation.

Please download this one which has everything for you to test within the _bin/debug_ folder: 
[Sample project](https://github.com/mkaring/ConfuserEx/files/4239320/TEMP.zip).

````C#
abstract class C : I<DayOfWeek>
{
	[My(Value = 1)]
	public abstract DayOfWeek T { get; }
}
sealed class D : C
{
	public override DayOfWeek T { get => DayOfWeek.Monday; }
}

[System.AttributeUsage(AttributeTargets.All, Inherited = true, AllowMultiple = true)]
sealed class MyAttribute : Attribute
{
	public int Value { get; set; }
}
// the following statement will crash the program after protection
Console.WriteLine((Attribute.GetCustomAttributes(typeof(D).GetProperties()[0], typeof(MyAttribute))[0] as MyAttribute).Value);
````

The cause of the exception is because the name of the renamed property in the class and the implemented interface was not identical, consequently, the `Attribute.GetCustomAttributes` method failed to find the inherited attribute from class `D`.

**Comment by mkaring** [comment]
I am able to reproduce the issue now. There is something very strange going on here.

If you add this line anywhere in the code:
```C#
Console.WriteLine(((MyAttribute) Attribute.GetCustomAttributes(typeof(C).GetProperties()[0], typeof(MyAttribute))[0]).Value);
```
(note that the class `C` is checked), the code you provided starts working. And this line can be added _anywhere_ and does not require to be called. I added into a method in a different class that is completely dead code and it still had the effect that you test starts working.

**Comment by mkaring** [comment]
I found the issue. The abstract properties and events were not handled properly during the rename phase. Their methods are processed correctly, but not the properties and events themselves. That is the reason why the "normal" runtime works fine, but processing the events by reflection does not.

The latest `master` branch build from the buildserver contains the fix. You'll find it here: [ConfuserEx - Appveyor][0]

[0]: https://ci.appveyor.com/project/mkaring/confuserex/branch/master/artifacts

**Comment by wmjordan** [comment]
Thank you for fixing this problem so quickly.

I checked the protected assembly and saw the abstract member was not renamed after the obfuscation by the latest version.

If we take a look at the problematic version (offered in my previous post) which was "protected" with the _debug_ renaming mode, we will find that the property `T` in the base class `C` and the interface `I<T>` was renamed to `_T`, but the one in the subclass `D` was not, and all of their underlying methods are not renamed (still get_T). The inconsistency may be the problem.

I guess, since the output target was an EXE file, all those members could be renamed actually, if all the interface, base class and subclass were carefully handled with the same renaming procedure. If we skip the renaming procedure simply because a class was an abstract one, the protection could be compromised.

**Comment by mkaring** [comment]
You are correct. All `abstract` members of a type are currently not renamed. I haven't changed this. You are correct that it's possible to change that, but that is a more extensive change and not in the scope of this issue.

I'll create a new issue for renaming the abstract members.

**Comment by wmjordan** [comment]
Alright, I will close this issue.

**Comment by wmjordan** [comment]
I found that this problem had not yet been fully solved.

If there's one more class between the abstract one and the sealed one, the reflection could still fail.

````C#
namespace ConsoleApp1
{
	interface I<TM>
	{
		TM T { get; }
	}
	abstract class C : I<DayOfWeek>
	{
		[My(Value = 1)]
		public abstract DayOfWeek T { get; }
	}
	class D : C
	{
		// this property should inherit the MyAttribute from its base class
		public override DayOfWeek T { get => DayOfWeek.Monday; }
	}
	// this should inherit T with the MyAttribute from its base class D, C
	sealed class E : D
	{
	}

	[System.AttributeUsage(AttributeTargets.All, Inherited = true, AllowMultiple = true)]
	sealed class MyAttribute : Attribute
	{
		public int Value { get; set; }
	}
	class Program
	{
		static void Main(string[] args) {
			// the following statement will crash the program after protection
			Console.WriteLine((Attribute.GetCustomAttributes(typeof(E).GetProperties()[0], typeof(MyAttribute))[0] as MyAttribute).Value);
		}
	}
}
````

**Comment by wmjordan** [comment]
Sorry to comment again. @mkaring do you have time looking into the last sample project which still produces this bug?

**Comment by mkaring** [comment]
I am looking at the problem right now. I'm able to reproduce the issue, but I'm still trying to find a way to fix it.

**Comment by mkaring** [comment]
@wmjordan I think I fixed it. Also, due to the changes I was able to enable the renaming for properties and events again, when they overwrite each other.
It would be great if you could verify if those changes work for your projects.

Find the download [here][0].

[0]: https://ci.appveyor.com/project/mkaring/confuserex/builds/32614127/artifacts

**Comment by wmjordan** [comment]
Thank you very much for looking into this.
I'd gotten the following error while I was dealing with one of my projects.

````
  Exception: System.NullReferenceException: Object reference not set to an instance of an object.
     at Confuser.Renamer.Analyzers.VTableAnalyzer.BelongsToEvent(EventDef eventDef, MethodDef methodDef)
     at Confuser.Renamer.Analyzers.VTableAnalyzer.<>c__DisplayClass2_0.<Analyze>b__1(EventDef e)
     at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
     at Confuser.Renamer.Analyzers.VTableAnalyzer.Analyze(INameService service, ICollection`1 modules, MethodDef method)
     at Confuser.Renamer.Analyzers.VTableAnalyzer.Confuser.Renamer.IRenamer.Analyze(ConfuserContext context, INameService service, ProtectionParameters parameters, IDnlibDef def)
     at Confuser.Renamer.AnalyzePhase.Analyze(NameService service, ConfuserContext context, ProtectionParameters parameters, IDnlibDef def, Boolean runAnalyzer)
     at Confuser.Renamer.AnalyzePhase.Execute(ConfuserContext context, ProtectionParameters parameters)
     at Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContext context)
     at Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context)
     at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token)

````

**Comment by wmjordan** [comment]
And another exception in another project:

````
  Exception: System.ArgumentNullException: Value cannot be null.
  Parameter name: baseMemberDef
     at Confuser.Renamer.References.MemberOverrideReference..ctor(IMemberDef thisMemberDef, IMemberDef baseMemberDef)
     at Confuser.Renamer.Analyzers.VTableAnalyzer.Analyze(INameService service, ICollection`1 modules, MethodDef method)
     at Confuser.Renamer.Analyzers.VTableAnalyzer.Confuser.Renamer.IRenamer.Analyze(ConfuserContext context, INameService service, ProtectionParameters parameters, IDnlibDef def)
     at Confuser.Renamer.AnalyzePhase.Analyze(NameService service, ConfuserContext context, ProtectionParameters parameters, IDnlibDef def, Boolean runAnalyzer)
     at Confuser.Renamer.AnalyzePhase.Execute(ConfuserContext context, ProtectionParameters parameters)
     at Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContext context)
     at Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context)
     at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token)
````

**Comment by mkaring** [comment]
The build you find [here][0] should handle those cases much better.

[0]: https://ci.appveyor.com/project/mkaring/confuserex/builds/32644049/artifacts

**Comment by wmjordan** [comment]
Still have problem.

Please test it with the following project.
[TEMP.zip](https://github.com/mkaring/ConfuserEx/files/4578509/TEMP.zip)

**Comment by mkaring** [comment]
There also is another problem. The way how the names of the members are lined up now breaks the support for reflection by name. The easy way around this, it just to disable renaming in case properties and events are affected, because those are the only kinds of reflections where the names have to line up as far as I can tell. However, that isn't really the way I want to go here...

**Comment by wmjordan** [comment]
I found that when I nested the `D2` class in the demo project into a static class `S<T>`, the property in the class could not get property renamed. If it was not nested, things were quite OK.

**Comment by wmjordan** [comment]
I am sorry that the above demo project was incorrect. Please use the following one.

[TEMP.zip](https://github.com/mkaring/ConfuserEx/files/4580767/TEMP.zip)

**Comment by wmjordan** [comment]
I found the nested class could be **improperly renamed**(?), maybe it was the reason why your previous fix of the abstract types could not be applied to the nested type.

If we open the protected assembly and we could see that the nested class had a redundant prefix, which was not in the original assembly.

![捕获](https://user-images.githubusercontent.com/12182730/81067354-266b3e80-8f11-11ea-806c-c59b3dcddea9.PNG)

**Comment by wmjordan** [comment]
I found the nested class could be **improperly renamed**(?), maybe it was the reason why your previous fix of the abstract types could not be applied to the nested type.

If we open the protected assembly and we could see that the nested class had a redundant prefix, which was not in the original assembly.

![捕获](https://user-images.githubusercontent.com/12182730/81067744-bad5a100-8f11-11ea-8bd9-8e15965ad321.PNG)

**Comment by mkaring** [comment]
@wmjordan I added a new commit that is now able to handle all of my test cases. It would be great if you could check the build in your project.

You can download it [here][0].

[0]: https://ci.appveyor.com/project/mkaring/confuserex/builds/33081876/artifacts

**Comment by wmjordan** [comment]
Thank you very much for working with this problem.
The new build still could not finish the protection phase. It was terminated with the following error:
````
[DEBUG] Executing 'Renaming' phase...
[DEBUG] Renaming...
[ERROR] Infinite loop detected while resolving name references.
````
However, no specific symbol name was given.

Could you please append the fully qualified symbol name being renamed into the message, so I can track down the one that causing the problem and make a demo project to reproduce the problem?

**Comment by mkaring** [comment]
@wmjordan: I added an extensive amount of information to the error message you are receiving. Could you please produce the issue again and check what it says now?

**Comment by wmjordan** [comment]
Sure. Could you please tell me where to download the new test version?

**Comment by mkaring** [comment]
@wmjordan: Ah. Sorry. The download is [here](https://ci.appveyor.com/project/mkaring/confuserex/builds/33227080/artifacts).

**Comment by wmjordan** [comment]
Thank you.

I'd gotten the following message, however, I could not figure out what containing type were those members belong to, since there are too many `Name` properties in my projects.

````
 [DEBUG] Renaming...
  [ERROR] Infinite loop detected while resolving name references.
  Processed definition: Original Name: Data; Name Hash: CB6899B
  Assembly: TheAssemblyNameHere
  Faulty References:
   - Member Override Reference(This Referenced Definition(Original Name: Data; Name Hash: 6BFF955F); Base Referenced Definition(Original Name: Data; Name Hash: 6BFF955F))
   - Member Override Reference(This Referenced Definition(Original Name: Data; Name Hash: CB6899B); Base Referenced Definition(Original Name: Data; Name Hash: CB6899B))
````

**Comment by mkaring** [comment]
@wmjordan: I added the type names to the output. This way you should be able to identify the affected properties.

Find the new build [here](https://ci.appveyor.com/project/mkaring/confuserex/builds/33235601/artifacts).

**Comment by wmjordan** [comment]
Got it.
It was weird.
The previous build stopped at the error of a property named `Data` and this time it stopped at another one like the following.

````
  Faulty References:
   - Member Override Reference(This Referenced Method(Original Name: X::get_Name; Name Hash: 1B881D15); Base Referenced Method(Original Name: X::get_Name; Name Hash: 1B881D15))
````

The property which caused trouble was in a `sealed class`, which had no base class, but had implemented two interfaces (and three more actually), both of which had the same property name.
My project was a console application which ran on .NET Framework 4.

Maybe we can construct a test case alike the following:

````C#
public sealed class C : IA, IB {
   public string N {get;set;} = "abc";
}

public interface IA {
    void M();
    string N{get;}
}
public interface IB {
    string N{get;}
}
````

**Comment by mkaring** [comment]
I think I finally got it now. It should now be able to handle what ever strange inheritance structure is applied. If it can't resolve something clearly, it will bail out can leave the parts that can't be renamed untouched. How ever in that case it will produce a warning message listing all the types and members that failed to rename properly.

In case something causes an unstable renaming situation, it will still fail as it did before. The reason is that the assembly is broken in case that happens. I hope that resolves the issue.

@wmjordan: Please have another try.

**Comment by wmjordan** [comment]
Thank you very much for addressing this issue.
I'd downloaded this new build and used it onto my production projects.
It did reported the following warning.

````
[WARN] Failed to rename all targeted members, because the references are blocking each other.
````
After that, 10 member names from various interfaces and classes were listed.

The compilation was finished eventually.
The compiled application appeared to be working.

**Comment by mkaring** [comment]
That's a start. But it still means that something is not resolved. Are the members listed and there inheriting members in different assemblies or something like this? 
Could you share the structure of the members and their inheritance?

**Comment by wmjordan** [comment]
Thank you for the hints. Maybe you don't need to FIX it at this moment.

Details:

Those members are rooted in an interface (9 classes implementing the same 1 interface), with a single property.

I observed the interface and the classes, and found the following.

The problematic interface is `IRoot`, which has a property `Count`.
The interface is implemented by a class `C<TKey,TValue>`, which implements `IExt<TKey,TValue>`.
The `IExt<TKey,TValue>` inherits from `IExt`, `IDictionary<TKey,TValue>` (external assembly).
`IExt` inherits from `IRoot`, thus it has a property named `Count`.
Obviously, `IDictionary<TKey,TValue>` has also a property named `Count`.
And `C<TKey,TValue>` has not explicitly implemented `IDictionary<TKey,TValue>.Count`.

Therefore, it is correct not to rename the property `Count` since it implements both a internal interface and a external interface.

````C#
interface IRoot { int Count { get; } } // THE interface in WARN
class C<TKey,TValue> : IExt<TKey,TValue> {
    public int Count { get; private set; }
    // other stuff...
}

interface IExt : IRoot { string Ext { get; } } // not listed in WARN
interface IExt<TKey,TValue>
   : IExt, System.Collections.Generics.IDictionary<TKey,TValue> { } // not listed in WARN
````

**Comment by wmjordan** [comment]
The information is quite helpful to address the problem.

**Comment by mkaring** [comment]
Okay, it's correct that it doesn't rename this, but it shouldn't list the issue either. The presence of an external interface should just block the entire inheritance structure from being renamed.

**Comment by wmjordan** [comment]
The definition of `C<TKey,TValue>` should be:

````C#
class C<TKey,TValue> : IExt<TKey,TValue>, IDictionary<TKey,TValue>, IDictionary {
  ....
}
````

Could it because that the class explicitly listing `IDictionary<TKey,TValue>` and `IDictionary` in its implemented interfaces which causes the _WARN_ list?

**Comment by mkaring** [comment]
It was plain luck that it worked in your case. It selected the property of the `IDictionary` to guide the naming by chance that that meant that it did not rename any of the properties. If it selects a property that is part of the obfuscated assembly, it will break it again.
I updated the unit test for this case and it did show just that behavior.

I updated the way how the restrictions on the renaming are exchanged between the members that are part of the inheritance and now it should work significantly better. Also that means that it shouldn't show any warning in regards to members that are not getting renamed.

@wmjordan: It would be great if you could give it another spin in your project and get back to me with the results. [Here is the latest build.][0]

[0]: https://ci.appveyor.com/project/mkaring/confuserex/builds/33855514/artifacts

**Comment by wmjordan** [comment]
Thank you for the update.
I downloaded the build and used it process my projects.
No [WARN] is displayed any more and the protected application was working well!
I'll deploy it to other servers and see whether the application is good either.

**Comment by mkaring** [comment]
@wmjordan: Any result on the wider deployment?

**Comment by wmjordan** [comment]
So far, so good.
Nothing wrong or weird.

**Comment by wmjordan** [comment]
Thank you very much for the hard work!

**Comment by mkaring** [comment]
Okay. In that case I hope for the best and release the new version later today ;)
